import { getDefaultStore } from "jotai";
import {
    deliveryRequestAtom,
    deliveryRequestAtom as writeDeliveryRequestAtom,
} from "../store/delivery";
import { userAtom } from "../store/user";
import axios from "axios";
import { API_URL } from "../const";
import { Clerk } from "@clerk/clerk-expo";

const store = getDefaultStore();

// Define the exact struct the LLM is instructed to return
export interface DissiActionPayload {
    action: string;
    args: any;
    message?: string; // Used for the conversational loop if missing info
}

/**
 * Parses and dispatches actions generated by the AI.
 *
 * @param payload The JSON payload from the LLM
 * @param navigation The react-navigation object to trigger UI changes
 * @param openRiderModal Callback to open the FindRiderSheet
 */
export const dispatchDissiAction = async (
    payload: DissiActionPayload,
    navigation: any,
    openRiderModal: () => void,
    getToken: () => Promise<string | null>,
) => {
    switch (payload.action) {
        case "FIND_RIDER": {
            // EXPECTED ARGS: { pickupLocation: string, dropoffLocation: string, packageType?: string }
            const currentReq = store.get(deliveryRequestAtom);

            store.set(writeDeliveryRequestAtom, {
                ...currentReq,
                pickupLocation:
                    payload.args.pickupLocation || currentReq.pickupLocation,
                dropoffLocation:
                    payload.args.dropoffLocation || currentReq.dropoffLocation,
                packageType: payload.args.packageType || currentReq.packageType,
            });

            // Trigger the UI flow
            openRiderModal();
            return { success: true, message: "Looking for a rider now." };
        }

        case "UPDATE_PROFILE": {
            // EXPECTED ARGS: { name: string }
            const currentUser = store.get(userAtom);
            if (!currentUser) {
                return { success: false, message: "User not logged in." };
            }

            try {
                const token = await getToken();
                // Assumes an endpoint exists; adjust to actual app endpoints if needed
                await axios.patch(
                    `${API_URL}/users/profile`,
                    {
                        fullName: payload.args.name,
                    },
                    {
                        headers: { Authorization: `Bearer ${token}` },
                    },
                );

                store.set(userAtom, {
                    ...currentUser,
                    fullName: payload.args.name,
                });
                return {
                    success: true,
                    message: `Profile name updated to ${payload.args.name}.`,
                };
            } catch (error) {
                console.error("Failed to update profile via Voice", error);
                return {
                    success: false,
                    message: "I couldn't update your profile right now.",
                };
            }
        }

        case "ASK_CLARIFICATION": {
            // DO NOTHING EXPLICITLY TO UI STATE, just return the message so it can be spoken/shown
            return {
                success: true,
                message: payload.message || "Could you clarify that?",
            };
        }

        default:
            console.warn(`[Dissi] Unknown action: ${payload.action}`);
            return {
                success: false,
                message: "I'm not sure how to do that yet.",
            };
    }
};
